components:
  schemas:
    RedfishError:
      description: The error payload from a Redfish service.
      properties:
        error:
          description: The properties that describe an error from a Redfish service.
          properties:
            '@Message.ExtendedInfo':
              description: An array of messages describing one or more error messages.
              items:
                $ref: Message.v1_2_0.yaml#/components/schemas/Message_v1_2_0_Message
              type: array
              x-longDescription: This property shall be an array of message objects
                describing one or more error messages.
            code:
              description: A string indicating a specific MessageId from a message
                registry.
              readOnly: true
              type: string
              x-longDescription: This property shall contain a string indicating a
                specific MessageId from a message registry.
            message:
              description: A human-readable error message corresponding to the message
                in a message registry.
              readOnly: true
              type: string
              x-longDescription: This property shall contain a human-readable error
                message corresponding to the message in a message registry.
          required:
          - code
          - message
          type: object
          x-longDescription: The Redfish Specification-described type shall contain
            properties that describe an error from a Redfish service.
      required:
      - error
      type: object
      x-longDescription: The Redfish Specification-described type shall contain an
        error payload from a Redfish service.
info:
  contact:
    name: DMTF
    url: https://www.dmtf.org/standards/redfish
  description: This contains the definition of a Redfish service.
  title: Redfish
  version: '2023.3'
  x-copyright: Copyright 2023 DMTF. For the full DMTF copyright policy, see http://www.dmtf.org/about/policies/copyright
openapi: 3.0.1
paths:
  /redfish/v1/Registries:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: MessageRegistryFileCollection.yaml#/components/schemas/MessageRegistryFileCollection_MessageRegistryFileCollection
          description: The response contains a representation of the MessageRegistryFileCollection
            resource
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedfishError'
          description: Error condition
  /redfish/v1/Registries/{MessageRegistryFileId}:
    get:
      parameters:
      - description: The value of the Id property of the MessageRegistryFile resource
        in: path
        name: MessageRegistryFileId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: MessageRegistryFile.v1_1_4.yaml#/components/schemas/MessageRegistryFile_v1_1_4_MessageRegistryFile
          description: The response contains a representation of the MessageRegistryFile
            resource
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedfishError'
          description: Error condition
